language: node_js
node_js:
  - "node"
cache:
  npm: true
  yarn: true
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: build
  on:
    branch: eleventy
